// --- Multilanguage Support ---
const supportedLanguages = ['en', 'es', 'fr', 'de', 'zh'];
const translations = {
    en: {
        title: "App & Game Platform",
        title_banner: "App & Game Platform",
        searchPlaceholder: "Search games...",
        search: "Search",
        reset: "Reset",
        previous: "Previous",
        next: "Next",
        page: "Page",
        of: "of",
        recommended: "Recommended Games",
        by: "By",
        tags: "Tags",
        description: "Description",
        themeNames: {
            default: "Default",
            dark: "Dark",
            light: "Light"
        },
        tagNames: {
            singleplayer: "Singleplayer",
            "mobile-friendly": "Mobile Friendly",
            docs: "Documentation",
            Aaron: "Aaron"
        },
        favourites: "Favourites",
        recentlyPlayed: "Recently Played",
        addFavourite: "Add to favourites",
        removeFavourite: "Remove from favourites",
        clear: "Clear",
        exportData: "Export Data",
        importData: "Import Data",
        timerStart: "Start Timer",
        timerStop: "Stop Timer",
        timerSetMinutes: "Set minutes",
        timerRemaining: "Time left",
        timerEndedTitle: "Time's Up!",
        timerEndedMsg: "Your game time is over. Please take a break.",
        timerReturn: "Return",
    },
    es: {
        title: "App & Game Platform",
        title_banner: "App & Game Platform",
        searchPlaceholder: "Buscar juegos...",
        search: "Buscar",
        reset: "Restablecer",
        previous: "Anterior",
        next: "Siguiente",
        page: "Página",
        of: "de",
        recommended: "Juegos recomendados",
        by: "Por",
        tags: "Etiquetas",
        description: "Descripción",
        themeNames: {
            default: "Predeterminado",
            dark: "Oscuro",
            light: "Claro"
        },
        tagNames: {
            singleplayer: "Un jugador",
            "mobile-friendly": "Compatible móvil",
            docs: "Documentación",
            Aaron: "Aaron"
        },
        favourites: "Favoritos",
        recentlyPlayed: "Jugados recientemente",
        addFavourite: "Agregar a favoritos",
        removeFavourite: "Quitar de favoritos",
        clear: "Limpiar",
        exportData: "Exportar datos",
        importData: "Importar datos",
        timerStart: "Iniciar temporizador",
        timerStop: "Detener temporizador",
        timerSetMinutes: "Establecer minutos",
        timerRemaining: "Tiempo restante",
        timerEndedTitle: "¡Se acabó el tiempo!",
        timerEndedMsg: "Tu tiempo de juego ha terminado. Por favor, toma un descanso.",
        timerReturn: "Regresar",
    },
    fr: {
        title: "App & Game Platform",
        title_banner: "App & Game Platform",
        searchPlaceholder: "Rechercher des jeux...",
        search: "Rechercher",
        reset: "Réinitialiser",
        previous: "Précédent",
        next: "Suivant",
        page: "Page",
        of: "sur",
        recommended: "Jeux recommandés",
        by: "Par",
        tags: "Tags",
        description: "Description",
        themeNames: {
            default: "Défaut",
            dark: "Sombre",
            light: "Clair"
        },
        tagNames: {
            singleplayer: "Solo",
            "mobile-friendly": "Mobile",
            docs: "Documentation",
            Aaron: "Aaron"
        },
        favourites: "Favoris",
        recentlyPlayed: "Récemment joués",
        addFavourite: "Ajouter aux favoris",
        removeFavourite: "Retirer des favoris",
        clear: "Effacer",
        exportData: "Exporter les données",
        importData: "Importer des données",
        timerStart: "Démarrer le minuteur",
        timerStop: "Arrêter le minuteur",
        timerSetMinutes: "Définir les minutes",
        timerRemaining: "Temps restant",
        timerEndedTitle: "Temps écoulé !",
        timerEndedMsg: "Votre temps de jeu est écoulé. Veuillez faire une pause.",
        timerReturn: "Retourner",
    },
    de: {
        title: "App & Game Platform",
        title_banner: "App & Game Platform",
        searchPlaceholder: "Spiele suchen...",
        search: "Suchen",
        reset: "Zurücksetzen",
        previous: "Zurück",
        next: "Weiter",
        page: "Seite",
        of: "von",
        recommended: "Empfohlene Spiele",
        by: "Von",
        tags: "Stichworte",
        description: "Beschreibung",
        themeNames: {
            default: "Standard",
            dark: "Dunkel",
            light: "Hell"
        },
        tagNames: {
            singleplayer: "Einzelspieler",
            "mobile-friendly": "Mobilfreundlich",
            docs: "Dokumentation",
            Aaron: "Aaron"
        },
        favourites: "Favoriten",
        recentlyPlayed: "Kürzlich gespielt",
        addFavourite: "Zu Favoriten hinzufügen",
        removeFavourite: "Aus Favoriten entfernen",
        clear: "Löschen",
        exportData: "Daten exportieren",
        importData: "Daten importieren",
        timerStart: "Timer starten",
        timerStop: "Timer stoppen",
        timerSetMinutes: "Minuten einstellen",
        timerRemaining: "Verbleibende Zeit",
        timerEndedTitle: "Zeit abgelaufen!",
        timerEndedMsg: "Ihre Spielzeit ist abgelaufen. Bitte machen Sie eine Pause.",
        timerReturn: "Zurückkehren",
    },
    zh: {
        title: "应用和游戏集",
        title_banner: "应用和游戏集",
        searchPlaceholder: "搜索游戏...",
        search: "搜索",
        reset: "重置",
        previous: "上一页",
        next: "下一页",
        page: "第",
        of: "共",
        recommended: "推荐游戏",
        by: "作者",
        tags: "标签",
        description: "简介",
        themeNames: {
            default: "默认",
            dark: "深色",
            light: "浅色"
        },
        tagNames: {
            singleplayer: "单人",
            "mobile-friendly": "移动端适配",
            docs: "文档",
            Aaron: "Aaron"
        },
        favourites: "收藏夹",
        recentlyPlayed: "最近玩过",
        addFavourite: "添加到收藏夹",
        removeFavourite: "从收藏夹移除",
        clear: "清除",
        exportData: "导出数据",
        importData: "导入数据",
        timerStart: "开始计时",
        timerStop: "停止计时",
        timerSetMinutes: "设置分钟数",
        timerRemaining: "剩余时间",
        timerEndedTitle: "时间到！",
        timerEndedMsg: "您的游戏时间已结束，请休息一下。",
        timerReturn: "返回",
    }
};