// --- Multilanguage Support ---
const supportedLanguages = ['en', 'es', 'fr', 'de', 'zh'];
const translations = {
    en: {
        title: "App & Game Platform",
        title_banner: "App & Game Platform",
        searchPlaceholder: "Search games...",
        search: "Search",
        reset: "Reset",
        previous: "Previous",
        next: "Next",
        page: "Page",
        of: "of",
        recommended: "Recommended Games",
        by: "By",
        tags: "Tags",
        description: "Description",
        themeNames: {
            default: "Default",
            dark: "Dark",
            light: "Light"
        },
        tagNames: {
            singleplayer: "Singleplayer",
            "mobile-friendly": "Mobile Friendly",
            docs: "Documentation",
            Aaron: "Aaron"
        },
        favourites: "Favourites",
        recentlyPlayed: "Recently Played",
        addFavourite: "Add to favourites",
        removeFavourite: "Remove from favourites",
        clear: "Clear",
        clearAll: "Clear All Data",
        exportData: "Export Data",
        importData: "Import Data",
        searchTags: "Search tags...",
        showAllTags: "Show All Tags",
        showFewerTags: "Show Fewer Tags",
        timerStart: "Start Timer",
        timerStop: "Stop Timer",
        timerSetMinutes: "Set minutes",
        timerRemaining: "Time left",
        timerEndedTitle: "Time's Up!",
        timerEndedMsg: "Your game time is over. Please take a break.",
        timerReturn: "Return",
        saveWindows: "Auto-save Windows",
        sortByName: "Name",
        sortByUpdated: "Last Updated",
        ascending: "Ascending",
        descending: "Descending",
        playTimeAnalytics: {
            enable: "Enable Play Time Analytics",
            totalSite: "Total Site Time",
            perGame: "Per Game/App Time",
            show: "Show Analytics",
            hide: "Hide Analytics",
            reset: "Reset Analytics",
            none: "No data yet."
        },
        randomGame: "Random Game",
        noGamesForRandom: "No games match current filters. Please reset filters.",
        openInNewTab: "Open in New Tab",
        copyUrl: "Copy URL",
        urlCopied: "URL Copied!",
        loading: "Loading...",
    },
    es: {
        title: "App & Game Platform",
        title_banner: "App & Game Platform",
        searchPlaceholder: "Buscar juegos...",
        search: "Buscar",
        reset: "Restablecer",
        previous: "Anterior",
        next: "Siguiente",
        page: "Página",
        of: "de",
        recommended: "Juegos recomendados",
        by: "Por",
        tags: "Etiquetas",
        description: "Descripción",
        themeNames: {
            default: "Predeterminado",
            dark: "Oscuro",
            light: "Claro"
        },
        tagNames: {
            singleplayer: "Un jugador",
            "mobile-friendly": "Compatible móvil",
            docs: "Documentación",
            Aaron: "Aaron"
        },
        favourites: "Favoritos",
        recentlyPlayed: "Jugados recientemente",
        addFavourite: "Agregar a favoritos",
        removeFavourite: "Quitar de favoritos",
        clear: "Limpiar",
        clearAll: "Borrar todos los datos",
        exportData: "Exportar datos",
        importData: "Importar datos",
        searchTags: "Buscar etiquetas...",
        showAllTags: "Mostrar Todas las Etiquetas",
        showFewerTags: "Mostrar Menos Etiquetas",
        timerStart: "Iniciar temporizador",
        timerStop: "Detener temporizador",
        timerSetMinutes: "Establecer minutos",
        timerRemaining: "Tiempo restante",
        timerEndedTitle: "¡Se acabó el tiempo!",
        timerEndedMsg: "Tu tiempo de juego ha terminado. Por favor, toma un descanso.",
        timerReturn: "Regresar",
        saveWindows: "Auto-guardar ventanas",
        sortByName: "Nombre",
        sortByUpdated: "Última actualización",
        ascending: "Ascendente",
        descending: "Descendente",
        playTimeAnalytics: {
            enable: "Activar análisis de tiempo de juego",
            totalSite: "Tiempo total en el sitio",
            perGame: "Tiempo por juego/app",
            show: "Mostrar análisis",
            hide: "Ocultar análisis",
            reset: "Restablecer análisis",
            none: "Sin datos aún."
        },
        randomGame: "Juego Aleatorio",
        noGamesForRandom: "Ningún juego coincide con los filtros actuales. Restablece los filtros.",
        openInNewTab: "Abrir en Nueva Pestaña",
        copyUrl: "Copiar URL",
        urlCopied: "¡URL Copiada!",
        loading: "Cargando...",
    },
    fr: {
        title: "App & Game Platform",
        title_banner: "App & Game Platform",
        searchPlaceholder: "Rechercher des jeux...",
        search: "Rechercher",
        reset: "Réinitialiser",
        previous: "Précédent",
        next: "Suivant",
        page: "Page",
        of: "sur",
        recommended: "Jeux recommandés",
        by: "Par",
        tags: "Tags",
        description: "Description",
        themeNames: {
            default: "Défaut",
            dark: "Sombre",
            light: "Clair"
        },
        tagNames: {
            singleplayer: "Solo",
            "mobile-friendly": "Mobile",
            docs: "Documentation",
            Aaron: "Aaron"
        },
        favourites: "Favoris",
        recentlyPlayed: "Récemment joués",
        addFavourite: "Ajouter aux favoris",
        removeFavourite: "Retirer des favoris",
        clear: "Effacer",
        clearAll: "Effacer toutes les données",
        exportData: "Exporter les données",
        importData: "Importer des données",
        searchTags: "Rechercher des tags...",
        showAllTags: "Afficher Tous les Tags",
        showFewerTags: "Afficher Moins de Tags",
        timerStart: "Démarrer le minuteur",
        timerStop: "Arrêter le minuteur",
        timerSetMinutes: "Définir les minutes",
        timerRemaining: "Temps restant",
        timerEndedTitle: "Temps écoulé !",
        timerEndedMsg: "Votre temps de jeu est écoulé. Veuillez faire une pause.",
        timerReturn: "Retourner",
        saveWindows: "Sauvegarde auto des fenêtres",
        sortByName: "Nom",
        sortByUpdated: "Dernière mise à jour",
        ascending: "Ascendant",
        descending: "Descendant",
        playTimeAnalytics: {
            enable: "Activer l'analyse du temps de jeu",
            totalSite: "Temps total sur le site",
            perGame: "Temps par jeu/app",
            show: "Afficher l'analyse",
            hide: "Masquer l'analyse",
            reset: "Réinitialiser l'analyse",
            none: "Pas encore de données."
        },
        randomGame: "Jeu Aléatoire",
        noGamesForRandom: "Aucun jeu ne correspond aux filtres actuels. Veuillez réinitialiser les filtres.",
        openInNewTab: "Ouvrir dans un Nouvel Onglet",
        copyUrl: "Copier l'URL",
        urlCopied: "URL Copiée !",
        loading: "Chargement...",
    },
    de: {
        title: "App & Game Platform",
        title_banner: "App & Game Platform",
        searchPlaceholder: "Spiele suchen...",
        search: "Suchen",
        reset: "Zurücksetzen",
        previous: "Zurück",
        next: "Weiter",
        page: "Seite",
        of: "von",
        recommended: "Empfohlene Spiele",
        by: "Von",
        tags: "Stichworte",
        description: "Beschreibung",
        themeNames: {
            default: "Standard",
            dark: "Dunkel",
            light: "Hell"
        },
        tagNames: {
            singleplayer: "Einzelspieler",
            "mobile-friendly": "Mobilfreundlich",
            docs: "Dokumentation",
            Aaron: "Aaron"
        },
        favourites: "Favoriten",
        recentlyPlayed: "Kürzlich gespielt",
        addFavourite: "Zu Favoriten hinzufügen",
        removeFavourite: "Aus Favoriten entfernen",
        clear: "Löschen",
        clearAll: "Alle Daten löschen",
        exportData: "Daten exportieren",
        importData: "Daten importieren",
        searchTags: "Tags suchen...",
        showAllTags: "Alle Tags Anzeigen",
        showFewerTags: "Weniger Tags Anzeigen",
        timerStart: "Timer starten",
        timerStop: "Timer stoppen",
        timerSetMinutes: "Minuten einstellen",
        timerRemaining: "Verbleibende Zeit",
        timerEndedTitle: "Zeit abgelaufen!",
        timerEndedMsg: "Ihre Spielzeit ist abgelaufen. Bitte machen Sie eine Pause.",
        timerReturn: "Zurückkehren",
        saveWindows: "Fenster automatisch speichern",
        sortByName: "Name",
        sortByUpdated: "Zuletzt aktualisiert",
        ascending: "Aufsteigend",
        descending: "Absteigend",
        playTimeAnalytics: {
            enable: "Spielzeit-Analyse aktivieren",
            totalSite: "Gesamte Seitenzeit",
            perGame: "Zeit pro Spiel/App",
            show: "Analyse anzeigen",
            hide: "Analyse ausblenden",
            reset: "Analyse zurücksetzen",
            none: "Noch keine Daten."
        },
        randomGame: "Zufälliges Spiel",
        noGamesForRandom: "Kein Spiel entspricht den aktuellen Filtern. Bitte Filter zurücksetzen.",
        openInNewTab: "In Neuem Tab Öffnen",
        copyUrl: "URL Kopieren",
        urlCopied: "URL Kopiert!",
        loading: "Wird geladen...",
    },
    zh: {
        title: "应用和游戏集",
        title_banner: "应用和游戏集",
        searchPlaceholder: "搜索游戏...",
        search: "搜索",
        reset: "重置",
        previous: "上一页",
        next: "下一页",
        page: "第",
        of: "共",
        recommended: "推荐游戏",
        by: "作者",
        tags: "标签",
        description: "简介",
        themeNames: {
            default: "默认",
            dark: "深色",
            light: "浅色"
        },
        tagNames: {
            singleplayer: "单人",
            "mobile-friendly": "移动端适配",
            docs: "文档",
            Aaron: "Aaron"
        },
        favourites: "收藏夹",
        recentlyPlayed: "最近玩过",
        addFavourite: "添加到收藏夹",
        removeFavourite: "从收藏夹移除",
        clear: "清除",
        clearAll: "清除所有数据",
        exportData: "导出数据",
        importData: "导入数据",
        searchTags: "搜索标签...",
        showAllTags: "显示所有标签",
        showFewerTags: "显示较少标签",
        timerStart: "开始计时",
        timerStop: "停止计时",
        timerSetMinutes: "设置分钟数",
        timerRemaining: "剩余时间",
        timerEndedTitle: "时间到！",
        timerEndedMsg: "您的游戏时间已结束，请休息一下。",
        timerReturn: "返回",
        saveWindows: "自动保存窗口",
        sortByName: "名称",
        sortByUpdated: "最后更新",
        ascending: "升序",
        descending: "降序",
        playTimeAnalytics: {
            enable: "启用游戏时间分析",
            totalSite: "站点总时长",
            perGame: "每个游戏/应用时长",
            show: "显示分析",
            hide: "隐藏分析",
            reset: "重置分析",
            none: "暂无数据。"
        },
        randomGame: "随机游戏",
        noGamesForRandom: "没有游戏符合当前筛选条件，请重置筛选。",
        openInNewTab: "在新标签页打开",
        copyUrl: "复制链接",
        urlCopied: "链接已复制！",
        loading: "加载中...",
    }
};